#!/usr/bin/env bash
set -ex

WANT_LIBSODIUM=1.0.8
WANT_LIBZMQ=4.1.4
WANT_LIBVIGOR=1.2.10

mkdir tmp
BUILD_PREFIX=$PWD/tmp

CONFIG_OPTS=()
CONFIG_OPTS+=("CFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CPPFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("CXXFLAGS=-I${BUILD_PREFIX}/include")
CONFIG_OPTS+=("LDFLAGS=-L${BUILD_PREFIX}/lib")
CONFIG_OPTS+=("PKG_CONFIG_PATH=${BUILD_PREFIX}/lib/pkgconfig")
CONFIG_OPTS+=("--prefix=${BUILD_PREFIX}")

LD_LIBRARY_PATH="${BUILD_PREFIX}/lib"
export LD_LIBRARY_PATH

# dep: libsodium
curl -Ls https://github.com/jedisct1/libsodium/releases/download/${WANT_LIBSODIUM}/libsodium-${WANT_LIBSODIUM}.tar.gz | tar -xz
(cd libsodium-${WANT_LIBSODIUM}; ./configure "${CONFIG_OPTS[@]}"; make install)

# dep: libzmq
curl -Ls http://download.zeromq.org/zeromq-${WANT_LIBZMQ}.tar.gz | tar -xz
(cd zeromq-${WANT_LIBZMQ}; ./configure "${CONFIG_OPTS[@]}" --with-libsodium=yes; make install)

# dep: libvigor
curl -Ls https://github.com/jhunt/libvigor/releases/download/v${WANT_LIBVIGOR}/ctap-${WANT_LIBVIGOR}.tar.gz | tar -xz
(cd libvigor-${WANT_LIBVIGOR}; ./configure "${CONFIG_OPTS[@]}"; make install)

./bootstrap
./configure "${CONFIG_OPTS[@]}"

make
make check
make install
