#!/bin/bash

DATADIR=$(mktemp -d)
DATAFILE=${DATADIR}/data
trap 'rm -rf ${DATADIR}' EXIT TERM QUIT INT

sleepcat() {
	sleep ${1:-1}
	cat
}

string_is() {
	got=$1
	expect=$2
	msg=${2:-strings should match}

	if [[ "${got}" != "${expect}" ]]; then
		echo >&2 "${msg}: FAILED"
		echo >&2 "  expected: '${expect}'"
		echo >&2 "       got: '${got}'"
		echo >&2
		echo FAIL
		exit 1
	fi
}

file_is_empty() {
	file=$1
	msg=${2:-$(basename ${file}) should be empty}
	if [[ -f ${file} && -s ${file} ]]; then
		echo >&2 "${msg}: FAILED"
		echo >&2 "   file was not empty.  it contained:"
		echo >&2 "   -----------------------------------------------"
		cat ${file} | sed -e 's/^/   /'
		echo >&2 "   -----------------------------------------------"
		echo >&2
		echo FAIL
		exit 1
	fi
}

line_ok() {
	file=$1
	line=$2
	expect=$3
	msg=${4:-$(basename ${file}):${line} should be "${expect}"}

	got=$(sed -n ${line}p ${file})
	if [[ "${got}" != "${expect}" ]]; then
		echo >&2 "${msg}: FAILED"
		echo >&2 "  expected '${expect}'"
		echo >&2 "       got '${got}'"
		echo FAIL
		exit 1
	fi
}
