#!/bin/bash
source ${srcdir}/t/lib

ENDPOINT="ipc://${DATADIR}/pipeline.1"
./ztk pull --bind ${ENDPOINT} > ${DATAFILE} &
PULL_PID=$!

sleepcat <<EOF | ./ztk push --connect ${ENDPOINT}
BEACON|12345
RETRANS|<whatever>|blah
PING
EOF
kill -TERM ${PULL_PID}

line_ok ${DATAFILE} 1 "BEACON|12345"
line_ok ${DATAFILE} 2 "RETRANS|<whatever>|blah"
line_ok ${DATAFILE} 3 "PING"


ENDPOINT="ipc://${DATADIR}/pipeline.2"
./ztk pull --connect ${ENDPOINT} > ${DATAFILE} &
PULL_PID=$!

sleepcat <<EOF | ./ztk push --bind ${ENDPOINT}
BEACON|12345
RETRANS|<whatever>|blah
PING
EOF
kill -TERM ${PULL_PID}

line_ok ${DATAFILE} 1 "BEACON|12345"
line_ok ${DATAFILE} 2 "RETRANS|<whatever>|blah"
line_ok ${DATAFILE} 3 "PING"

exit 0
# vim:ft=sh
